MAC package fixes

diff --git a/build/bin/makeInstall b/build/bin/makeInstall
--- a/build/bin/makeInstall
+++ b/build/bin/makeInstall
@@ -57,7 +57,7 @@ processPackage() {
         [ "$QUIET" = 0 ] && log ${VERB} package/$1.files ...
         . "package/$1.files"
     else
-        echo -e "\nCan't open $fileList. Exiting." 1>&2
+        echo -e "\nCan't open $1.files. Exiting." 1>&2
         exit 255
     fi 
 }
