Get Native build working

diff --git a/build/bin/nativeBuild b/build/bin/nativeBuild
--- a/build/bin/nativeBuild
+++ b/build/bin/nativeBuild
@@ -1,14 +1,19 @@
 #!/bin/bash
 #
-#   Build a project using the native IDE (only)
+#   Build a project using the native IDE
 #
-#   Currently only supports Visual Studio on Windows
+#   Currently supports Visual Studio, MSBuild and XCode
 #   This is an internal-script used when testing only
 #
 
-. build/bin/buildConfig.sh
+if [ -f out/inc/buildConfig.h ] ; then
+    . `cacheConfig out/inc/buildConfig.h`
+else
+    . build/bin/buildConfig.sh
+fi
 
-VS="/Program Files/Microsoft Visual Studio 8/Common7/IDE/devenv.exe"
+VS="/Program Files/Microsoft Visual Studio 10/Common7/IDE/devenv.exe"
+MB="c:/Windows/Microsoft.NET/Framework/v4.0.30319/msbuild.exe"
 
 log() {
     tag=$1
@@ -16,7 +21,7 @@ log() {
     printf "%12s %s\n" $tag "$*"
 }
 
-winBuild() {
+vsBuild() {
     local status=0
     if [ -x "${VS}" ] ; then
         if [ ! -f src/include/buildConfig.save ] ; then
@@ -48,8 +53,6 @@ winBuild() {
         fi
         rm -fr projects/WIN/*/Win32
 
-        echo TESTING TARGETS
-
         status=0
         for f in appweb cgiProgram ejs ejsc ejsmod ejssql http httpPassword makerom testAppweb
         do
@@ -61,6 +64,55 @@ winBuild() {
         echo STATUS $status
     fi
     exit $status
+}
+
+
+msBuild() {
+    local status=0
+
+    touch projects/WIN/${BLD_PRODUCT}-all/buildConfig.default
+    log "[Test]" "Building ${BLD_PRODUCT}-all VS project"
+    rm -fr projects/WIN/*/Win32
+    "${VS}" projects/WIN/${BLD_PRODUCT}-all/*.sln /clean
+    if [ $? != 0 ] ; then
+        echo Failed to clean: "${VS}" projects/WIN/${BLD_PRODUCT}-all/*.sln /clean
+        exit 255
+    fi
+    "${VS}" projects/WIN/${BLD_PRODUCT}-all/*.sln /build
+    if [ $? != 0 ] ; then
+        echo Failed to build: "${VS}" projects/WIN/${BLD_PRODUCT}-all/*.sln /build
+        exit 255
+    fi
+    rm -fr projects/WIN/*/Win32
+    status=0
+    for f in appweb cgiProgram ejs ejsc ejsmod ejssql http httpPassword makerom testAppweb
+    do
+        if [ ! -x "$BLD_BIN_DIR/${f}${BLD_EXE}" ] ; then
+            echo Missing target $BLD_BIN_DIR/${f}${BLD_EXE} >&2
+            status=255
+        fi
+    done
+    echo STATUS $status
+    exit $status
+}
+
+winBuild() {
+    local status=0
+    if [ -f buildConfig.make ] ; then
+        if [ ! -x "${VS}" ] ; then
+            echo "Can't find $VS" >&2
+            exit 255
+        else
+            vsBuild
+        fi
+    else
+        if [ ! -x "${MB}" ] ; then
+            echo "Can't find $MB" >&2
+            exit 255
+        else
+            msBuild
+        fi
+    fi
 }
 
 macBuild() {
