Fix windows pmaker probe

diff --git a/package/LINUX/deb.bin/postinst b/package/LINUX/deb.bin/postinst
--- a/package/LINUX/deb.bin/postinst
+++ b/package/LINUX/deb.bin/postinst
@@ -5,12 +5,12 @@
 #	Copyright (c) Embedthis Software LLC, 2003-2012. All Rights Reserved.
 #
 
-BLD_PRODUCT=${settings.product}
-BLD_NAME="${settings.title}"
-BLD_BIN_PREFIX="${prefixes.bin}"
-BLD_LIB_PREFIX="${prefixes.lib}"
-BLD_LOG_PREFIX="${prefixes.log}"
-BLD_SPL_PREFIX="${prefixes.spool}"
+BIT_PRODUCT=${settings.product}
+BIT_NAME="${settings.title}"
+BIT_BIN_PREFIX="${prefixes.bin}"
+BIT_LIB_PREFIX="${prefixes.lib}"
+BIT_LOG_PREFIX="${prefixes.log}"
+BIT_SPL_PREFIX="${prefixes.spool}"
 
 ###############################################################################
 
@@ -32,13 +32,13 @@ setPerms() {
 		fi
 	done
 	if [ "$username" = "" -o "$groupname" = "" ] ; then
-		echo "Can't find a suitable user/group for $BLD_PRODUCT" 1>&2
+		echo "Can't find a suitable user/group for $BIT_PRODUCT" 1>&2
 		exit 255
 	fi
-    mkdir -p "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
-    chown $username "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
-    chgrp $groupname "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
-    chmod 755 "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
+    mkdir -p "$BIT_SPL_PREFIX" "$BIT_SPL_PREFIX/cache" "$BIT_LOG_PREFIX"
+    chown $username "$BIT_SPL_PREFIX" "$BIT_SPL_PREFIX/cache" "$BIT_LOG_PREFIX"
+    chgrp $groupname "$BIT_SPL_PREFIX" "$BIT_SPL_PREFIX/cache" "$BIT_LOG_PREFIX"
+    chmod 755 "$BIT_SPL_PREFIX" "$BIT_SPL_PREFIX/cache" "$BIT_LOG_PREFIX"
 }
 
 ###############################################################################
@@ -53,14 +53,14 @@ case $action in
 	configure)							# when new
         setPerms
 		oldVersion=$2
-        "$BLD_BIN_PREFIX/linkup" Install /
+        "$BIT_BIN_PREFIX/linkup" Install /
         appman -v install
         if [ "$APPWEB_DONT_START" != 1 ] ; then
             appman enable
             appman start
         fi
         echo
-		echo "$BLD_NAME installation successful."
+		echo "$BIT_NAME installation successful."
 		;;
 	abort-upgrade)						# when old
 		;;
