Update Makefile.top

diff --git a/build/make/Makefile.top b/build/make/Makefile.top
--- a/build/make/Makefile.top
+++ b/build/make/Makefile.top
@@ -134,11 +134,45 @@ package-only:
 	fakePriv $(BLD_TOOLS_DIR)/makePackage --root=$(PKG_DIR) $(PACKS)
 
 packageExtra:
+	echo BUILD_DEPTH $(BUILD_DEPTH)
 	if [ "$(BUILD_DEPTH)" -ge 2 ] ; then \
 		mkdir -p $(BLD_TOP)/releases ; \
 		export OPTIONS=$(OPTIONS) TRACE=$(TRACE) ; \
 		fakePriv "$(BLD_TOP)/build/bin/makeInstall --root=$(PKG_DIR) $(INS_WITH) --package $(PACKS) && \
 			$(BLD_TOOLS_DIR)/makePackage --root=$(PKG_DIR) $(PACKS)" ; \
+	else \
+		echo "Packaging skipped at build depth $(BUILD_DEPTH) ; \
+	fi
+
+upload:
+	echo BUILD_DEPTH $(BUILD_DEPTH)
+	if [ "$(BUILD_DEPTH)" -lt 2 ] ; then \
+		echo "Skip upload for BUILD_DEPTH $(BUILD_DEPTH)" >&2; \
+	else \
+		if [ "$(BUILD_UPLOAD)" = "" ] ; then \
+			echo "Can't upload: BUILD_UPLOAD is not defined" >&2; \
+			exit 2 ; \
+		fi ; \
+		cd releases >/dev/null 2>&1 ; \
+		if ls $(IMG_NAME)* >/dev/null 2>&1 ; then \
+			for name in $(IMG_NAME)* md5-$(IMG_NAME)* ; \
+			do \
+				chmod 664 $$name ; \
+				echo http --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
+				http -q --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
+			done ; \
+		fi ; \
+	fi ; \
+	if [ "$(BUILD_UPLOAD_SOURCE)" = "true" ] ; then \
+		cd releases >/dev/null 2>&1 ; \
+		if ls $(IMG_NAME)* >/dev/null 2>&1 ; then \
+			for name in $(SRC_NAME)* md5-$(SRC_NAME)* ; \
+			do \
+				chmod 664 $$name ; \
+				echo http --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
+				http -q --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
+			done ; \
+		fi ; \
 	fi
 
 testExtraExtra:
@@ -285,31 +319,3 @@ incVersion:
 	sed s/BLD_NUMBER=\"$(BLD_NUMBER)\"/BLD_NUMBER=\"$${num}\"/ </tmp/build$$$$.tmp >build/product.config
 	./configure
 
-upload:
-	if [ "$(BUILD_DEPTH)" -le 2 ] ; then \
-		echo "Skip upload for BUILD_DEPTH $(BUILD_DEPTH)" >&2; \
-	else \
-		if [ "$(BUILD_UPLOAD)" = "" ] ; then \
-			echo "Can't upload: BUILD_UPLOAD is not defined" >&2; \
-			exit 2 ; \
-		fi
-		cd releases >/dev/null 2>&1 ; \
-		if ls $(IMG_NAME)* >/dev/null 2>&1 ; then \
-			for name in $(IMG_NAME)* md5-$(IMG_NAME)* ; \
-			do \
-				chmod 664 $$name ; \
-				echo http --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
-				http --log stdout:5 -q --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
-			done ; \
-		fi ; \
-	if [ "$(BUILD_UPLOAD_SOURCE)" = "true" ] ; then \
-		cd releases >/dev/null 2>&1 ; \
-		if ls $(IMG_NAME)* >/dev/null 2>&1 ; then \
-			for name in $(SRC_NAME)* md5-$(SRC_NAME)* ; \
-			do \
-				chmod 664 $$name ; \
-				echo http --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
-				http --log stdout:5 -q --upload --form "server=`hostname`&key=$(BUILD_KEY)" $$name $(BUILD_UPLOAD); \
-			done ; \
-		fi ; \
-	fi
