Refine test-install-*

diff --git a/build/make/Makefile.appweb b/build/make/Makefile.appweb
--- a/build/make/Makefile.appweb
+++ b/build/make/Makefile.appweb
@@ -5,6 +5,131 @@
 #
 
 #
+#	Top level test targets to test installing and removing packages
+#
+testExtra::
+	if [ "$(BUILD_DEPTH)" -ge 3 ] ; then \
+		$(MAKE) uninstall ; \
+		$(MAKE) test-uninstalled ; \
+		$(MAKE) test-install-package ; \
+		$(MAKE) test-installed ; \
+		$(MAKE) test-uninstall-package ; \
+		$(MAKE) test-uninstalled ; \
+		$(MAKE) test-install-native-package ; \
+		$(MAKE) test-installed ; \
+		$(MAKE) test-uninstall-native-package ; \
+		$(MAKE) test-uninstalled ; \
+	fi
+
+NATIVE_BUILD	=0
+ifeq    ($(BLD_HOST_OS),WIN)
+	NATIVE_BUILD=1
+endif
+ifeq    ($(BLD_HOST_OS),MACOSX)
+	NATIVE_BUILD=1
+endif
+
+test-projects:
+ifeq    ($(NATIVE_BUILD),1)
+	if [ "$(BUILD_DEPTH)" -ge 3 ] ; then \
+		$(BLD_TOOLS_DIR)/nativeBuild ; \
+	fi
+endif
+
+test-install-package:
+	set -e ; name="$(BASE_NAME).tgz" ; \
+	dir=/tmp/$(BLD_PRODUCT)-$$$$ ; \
+	rm -rf $$dir ; mkdir -p $$dir ; \
+	tar -C $$dir -zxf $(BLD_OUT_DIR)/releases/$$name ; \
+	cd $$dir >/dev/null 2>&1 ; \
+	priv "$(BLD_PRODUCT)_HEADLESS=1 ./install" ; \
+	rm -rf $$dir
+
+test-uninstall-package:
+	set -e ; name="$(BASE_NAME).tgz" ; \
+	dir=/tmp/$(BLD_PRODUCT)-$$$$ ; \
+	rm -rf $$dir ; mkdir -p $$dir ; \
+	tar -C $$dir -zxf $(BLD_OUT_DIR)/releases/$$name ; \
+	cd $$dir >/dev/null 2>&1 ; \
+	priv "$(BLD_PRODUCT)_HEADLESS=1 ./uninstall" ; \
+	rm -rf $$dir
+
+test-install-native-package:
+	set -e ; \
+	if [ $(BLD_HOST_OS) = WIN ] ; then \
+		rm -fr "$(STAGE_DIR)/*" ; \
+		name="$(BASE_NAME).exe.zip" ; \
+		cp WIN/unattended.ans $(BLD_OUT_DIR)/releases/$$name "$(STAGE_DIR)" ; cd "$(STAGE_DIR)" ; \
+		unzip -q -o $$name ; \
+		echo "Dir=$(STAGE_DIR)" >>unattended.ans ; \
+		./$(BASE_NAME).exe /loadinf=/tmp/unattended.ans /silent ; \
+	elif [ $(BLD_HOST_OS) = MACOSX ] ; then \
+		set -x ; \
+		hdiutil eject /Volumes/$(BLD_PRODUCT)-$(BLD_VERSION) >/dev/null 2>&1 || true ; \
+		hdid $(BLD_OUT_DIR)/releases/$(BASE_NAME).dmg >/dev/null ; \
+		priv installer -package /Volumes/$(BLD_PRODUCT)-$(BLD_VERSION)/$(BLD_PRODUCT).mpkg -target /; \
+		hdiutil eject /Volumes/$(BLD_PRODUCT)-$(BLD_VERSION) >/dev/null 2>&1 ; \
+	else \
+		name="$(BASE_NAME).tgz" ; \
+		tar -C /tmp xvfz $(BLD_OUT_DIR)/releases/$$name ; \
+		priv $(BLD_PRODUCT)_HEADLESS=1 ./install ; \
+	fi
+
+test-uninstall-native-package:
+	set -e ; \
+	if [ $(BLD_HOST_OS) = WIN ] ; then \
+		if [ ! -x "$(STAGE_DIR)/unins000.exe" ] ; then \
+			echo "Can't find $(STAGE_DIR)/unins000.exe to uninstall" ; \
+			exit 255 ; \
+		fi ; \
+		"$(STAGE_DIR)/unins000.exe" /silent ; \
+		rm -fr "$(STAGE_DIR)/*" ; \
+	else \
+		name="$(BASE_NAME).tgz" ; \
+		dir=/tmp/$(BLD_PRODUCT)-$$$$ ; \
+		rm -rf $$dir ; mkdir -p $$dir ; \
+		tar -C $$dir -zxf $(BLD_OUT_DIR)/releases/$$name ; \
+		cd $$dir >/dev/null 2>&1 ; \
+		priv "$(BLD_PRODUCT)_HEADLESS=1 ./uninstall" ; \
+		rm -rf $$dir ; \
+	fi
+
+test-installed:
+	set -e ; \
+	complete=1 ; \
+	for dir in $(BLD_CFG_PREFIX) $(BLD_BIN_PREFIX) $(BLD_INC_PREFIX) \
+		$(BLD_LIB_PREFIX) $(BLD_LOG_PREFIX) $(BLD_MAN_PREFIX) $(BLD_PRD_PREFIX) \
+		$(BLD_VER_PREFIX) $(BLD_WEB_PREFIX) ; \
+	do \
+		if [ ! -x $$dir ] ; then \
+			echo Missing directory: $$dir ; \
+			complete=0 ; \
+		fi ; \
+	done ; \
+	[ $$complete = 0 ] && exit 255 ; \
+	sleep 5 ; \
+	port=$(BLD_HTTP_PORT) ; \
+	http -q $$port/index.html ; \
+	http -q $$port/test/test.ejs ; \
+	http -q $$port/test/test.esp ; \
+	http -q $$port/test/test.php ; \
+	http -q $$port/test/test.cgi ; \
+	http -q $$port/test/test.pl ; \
+	http -q $$port/test/test.py ; \
+	echo Installed
+
+test-uninstalled:
+	partial=0 ; \
+	for dir in $(BLD_CFG_PREFIX) $(BLD_BIN_PREFIX) $(BLD_INC_PREFIX) $(BLD_LIB_PREFIX) $(BLD_LOG_PREFIX) \
+		$(BLD_MAN_PREFIX) $(BLD_PRD_PREFIX) $(BLD_VER_PREFIX) $(BLD_WEB_PREFIX) ; do \
+		if [ -x $$dir ] ; then \
+			partial=1 ; \
+			echo Directory present: $$dir ; \
+		fi ; \
+	done ; \
+	[ $$partial = 1 ] && exit 255 ; \
+	echo Uninstalled
+#
 #	Convenient configure targets
 #
 config:
@@ -215,29 +340,3 @@ uclinuxCheck:
 		exit 2 ; \
 	fi
 endif
-
-checkInstalled: installedFiles
-
-installedFiles:
-	( \
-	for d in $(BLD_CFG_PREFIX) $(BLD_BIN_PREFIX) $(BLD_DOC_PREFIX) $(BLD_INC_PREFIX) $(BLD_JEM_PREFIX) \
-		$(BLD_LIB_PREFIX) $(BLD_LOG_PREFIX) $(BLD_MAN_PREFIX) $(BLD_PRD_PREFIX) \
-		$(BLD_VER_PREFIX) $(BLD_WEB_PREFIX) /var/log /var/www /usr/share /usr/share/doc /usr/include /var/lib /var/spool \
-		/usr/local/bin/appweb /usr/local/bin/auth /usr/local/bin/http /usr/local/bin/esp ; \
-		do \
-			if [ "`echo $$d/$(BLD_PRODUCT)*`" != $$d/$(BLD_PRODUCT)'*' ] ; then \
-				eval echo "$$d/$(BLD_PRODUCT)*" ; \
-				continue ; \
-			fi ; \
-			if [ -x "$$d/$(BLD_PRODUCT)" ] ; then \
-				echo "$$d/$(BLD_PRODUCT)" ; \
-				continue ; \
-			fi ; \
-		done ; \
-		for d in "$(BLD_CFG_PREFIX)" "$(BLD_DOC_PREFIX)" "$(BLD_INC_PREFIX)" "$(BLD_LIB_PREFIX)" "$(BLD_LOG_PREFIX)" \
-			"$(BLD_SAM_PREFIX)" "$(BLD_SRC_PREFIX)" ; \
-		do \
-			[ -x "$$d" ] && echo "$$d" || true; \
-		done ; \
-	) | sort | uniq
-
