Update deps

diff --git a/build/components/cc b/build/components/cc
--- a/build/components/cc
+++ b/build/components/cc
@@ -101,10 +101,16 @@ setCompilerOptions()
             echo -e "    Checking for compiler -Wno-unused-result support"
             # echo -e "        ${cc}" -Werror -Wall -Wno-unused-result -c $file "\n"
         fi
-        echo -e "#include <stdio.h>\n#include <unistd.h>\nint main() { write(1, \"abc\", 3); return 0; }\n" >$file
+        echo -e "#include <stdio.h>\n#include <stdlib.h>\nint main() { realloc(0, 1024); return 0; }\n" >$file
+        #
+        #   Test that it passes with -Wno-unused-result and that it fails without it
+        #
         eval \"${cc}\" -Werror -Wall -Wno-unused-result -c $file >/dev/null 2>&1
         if [ $? = 0 ] ; then
-            eval $hasWarnUnused=1
+            eval \"${cc}\" -Werror -Wall -c $file >/dev/null 2>&1
+            if [ $? != 0 ] ; then
+                eval $hasWarnUnused=1
+            fi
         fi
 
         #
