VxWorks building on Linux updates

diff --git a/build/components/vxworks b/build/components/vxworks
--- a/build/components/vxworks
+++ b/build/components/vxworks
@@ -4,13 +4,25 @@
 defineComponent() {
 	local path partial
 
+    path="${1:-.}"
     if [ $KIND = "BUILD" -a $BLD_CROSS = 1 ] ; then
         echo "only used as a host component"
         return 0
     fi
-    path=`probe --name vxworks --dir --search "$1" "target/h/vxWorks.h"`
+    if [ "$WIND_BASE" != "" ] ; then
+        if [ "$WIND_HOME" = "" ] ; then
+            WIND_HOME=${WIND_BASE%/*}
+        fi
+        if [ "$WIND_PLATFORM" = "" ] ; then
+            WIND_PLATFORM=${WIND_BASE##*/}
+        fi
+    fi
+    search="$path:$WIND_BASE:$SEARCH_PATH"
+
+    path=`probe --name vxworks --dir --search "$search" "target/h/vxWorks.h"`
     if [ "$path" = "" ] ; then
         warnComponent "VxWorks" \
+            "Searching for target/h/vxWorks.h" \
             "Set WIND_HOME to the VxWorks directory containing the \"target\" directory (${partial})\n" \
             "This is usually /Tornado or /WindRiver/VxWorks\n"
         return
@@ -26,20 +38,28 @@ defineComponent() {
 
 setVxEnv()
 {
-    local file cc version file cc bldPath  path search
+    local file cc version file cc bldPath path search
 
 	path="$1"
 	WIND_BASE="$path"
+    WIND_PLATFORM=${WIND_BASE##*/}
 
     case $BLD_BUILD_OS in
     WIN|CYGWIN)
-        BLD_BUILD_SYSTEM_VX=x86-win32
+        WIND_HOST_TYPE=x86-win32
         ;;
     LINUX)
-        BLD_BUILD_SYSTEM_VX=x86-linux
+        if [ -x $path/host/x86-linux ] ; then
+            WIND_HOST_TYPE=x86-linux
+        elif [ -x $path/host/x86-linux2 ] ; then
+            WIND_HOST_TYPE=x86-linux2
+        else
+            echo "Can't determine WIND_HOST_TYPE: $path"
+            exit 255
+        fi
         ;;
     SOLARIS*)
-        BLD_BUILD_SYSTEM_VX=solaris2
+        WIND_HOST_TYPE=solaris2
         ;;
     *)
         echo "$BLD_BUILD_OS is an not a supported O/S for VxWorks cross compilation"
@@ -59,6 +79,8 @@ setVxEnv()
         echo "Cant find version.h at $version"
         exit 255
     fi
+    BLD_HOST_DIST=WindRiver
+    BLD_HOST_DIST_VER=$version
 
 	#
 	#	Tornado sets both HOME and BASE to /tornado
@@ -69,24 +91,19 @@ setVxEnv()
 	else
 		WIND_HOME="$path"
 	fi
-
-    WIND_HOST_TYPE="$BLD_BUILD_SYSTEM_VX"
-    BLD_HOST_DIST=WindRiver
-    BLD_HOST_DIST_VER=$version
-
+    BLD_BUILD_SYSTEM_VX=$WIND_HOST_TYPE
+	eval WIND_GNU_PATH=\"$WIND_HOME/gnu/*-${WIND_PLATFORM}\"
 	eval BLD_${kind}_IFLAGS=\"$BLD_HOST_IFLAGS $CFG_HOST_VXWORKS_IFLAGS\"
 
 	#
 	#	Update search path for base tools to use
 	#
     search="
-		'\$WIND_HOME/gnu/*/\$BLD_BUILD_SYSTEM_VX/bin'
-		'\$WIND_HOME/gnu/*/\$BLD_BUILD_SYSTEM_VX/\$BLD_HOST_SYSTEM/bin'
-		'\$WIND_HOME/\$BLD_HOST_DIST-\$BLD_HOST_DIST_VER/host/\$BLD_BUILD_SYSTEM_VX/bin'
-		'\$WIND_HOME/\$BLD_HOST_DIST-\$BLD_HOST_DIST_VER/host/resource/hutils/tcl'
-		'\$WIND_HOME/workbench*/foundation/*/\$BLD_BUILD_SYSTEM_VX/bin'
-		'\$WIND_HOME/host/*/bin'
-		'\$WIND_HOME/host/*/\$BLD_HOST_SYSTEM/bin'
+		'\$WIND_GNU_PATH/\$WIND_HOST_TYPE/bin'
+		'\$WIND_GNU_PATH/\$WIND_HOST_TYPE/\$BLD_HOST_SYSTEM/bin'
+		'\$WIND_BASE/host/\$WIND_HOST_TYPE/bin'
+		'\$WIND_BASE/host/resource/hutils/tcl'
+		'\$WIND_HOME/workbench*/foundation/*/\$WIND_HOST_TYPE/bin'
 	"
 	SEARCH_PATH="$SEARCH_PATH:`convertSearchPath "$search"`"
 
@@ -99,7 +116,7 @@ setVxEnv()
 	fi
 
 	#
-	#	Export so the "cc" component file can actually run the compiler
-	#
-	export WIND_HOME WIND_BASE
+	#	Export so the "cc" component file can run the compiler
+    #
+	export WIND_HOME WIND_BASE WIND_HOST_TYPE WIND_PLATFORM WIND_GNU_PATH 
 }
