Update mac packaging

diff --git a/package/MACOSX/scripts/postflight b/package/MACOSX/scripts/postflight
--- a/package/MACOSX/scripts/postflight
+++ b/package/MACOSX/scripts/postflight
@@ -6,16 +6,19 @@
 #
 ###############################################################################
 
+echo @@@@@ postflight
+set -x
+
 PKG_DIR="$1"
 INS_DIR="$2"
-path="${INS_DIR}!!ORIG_BLD_PREFIX!!"
 
-BLD_PRODUCT=!!BLD_PRODUCT!!
-BLD_NAME=!!BLD_NAME!!
-BLD_LIB_PREFIX="!!ORIG_BLD_LIB_PREFIX!!"
-BLD_LOG_PREFIX="!!ORIG_BLD_LOG_PREFIX!!"
-BLD_SPL_PREFIX="!!ORIG_BLD_SPL_PREFIX!!"
-BIN="!!ORIG_BLD_BIN_PREFIX!!"
+COMPANY="${settings.company}"
+PRODUCT="${settings.product}"
+NAME="${settings.title}"
+LIB_PREFIX="${prefixes.lib}"
+LOG_PREFIX="${prefixes.log}"
+SPL_PREFIX="${prefixes.spool}"
+BIN_DIR="${prefixes.bin}"
 
 ###############################################################################
 
@@ -37,15 +40,15 @@ setPerms() {
 		fi
 	done
 	if [ "$username" = "" -o "$groupname" = "" ] ; then
-		echo "Can't find a suitable user/group for $BLD_NAME" 1>&2
+		echo "Can't find a suitable user/group for $NAME" 1>&2
 		exit 255
 	fi
-    mkdir -p "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
-    chown $username "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
-    chgrp $groupname "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
-    chmod 755 "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
+    mkdir -p "$SPL_PREFIX" "$SPL_PREFIX/cache" "$LOG_PREFIX"
+    chown $username "$SPL_PREFIX" "$SPL_PREFIX/cache" "$LOG_PREFIX"
+    chgrp $groupname "$SPL_PREFIX" "$SPL_PREFIX/cache" "$LOG_PREFIX"
+    chmod 755 "$SPL_PREFIX" "$SPL_PREFIX/cache" "$LOG_PREFIX"
 
-    chmod 644 /Library/LaunchDaemons/com.!!BLD_COMPANY!!.!!BLD_PRODUCT!!.plist
+    chmod 644 /Library/LaunchDaemons/com.${COMPANY}.${PRODUCT}.plist
 }
 
 ###############################################################################
@@ -56,16 +59,15 @@ setPerms() {
 #
 #   Link current versions to /usr/local/bin
 #
-${BIN}/linkup Install
+${BIN_DIR}/linkup Install
 
 setPerms
 
 #
 #   Install, enable and start launch daemon
 #
-$BIN/appman install
-$BIN/appman enable
-$BIN/appman start
-# launchctl load -w /Library/LaunchDaemons/com.!!BLD_COMPANY!!.!!BLD_PRODUCT!!.plist
+${BIN_DIR}/appman install
+${BIN_DIR}/appman enable
+${BIN_DIR}//appman start
 
 exit 0
